# Generated by Django 2.1.2 on 2018-11-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productxdetailimage',
            name='display',
        ),
    ]
