# Generated by Django 2.1.2 on 2018-11-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_productxdetailimage_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productxdetailimage',
            name='image',
            field=models.ImageField(upload_to='shop/images'),
        ),
    ]
